version: "3.7"

services:
  anvil:
    image: ghcr.io/foundry-rs/foundry
    #build: ./anvil/.
    command: anvil --host 0.0.0.0 -p 8545 --mnemonic "test test test test test test test test test test test junk"
    ports:
      - 8545:8545
    environment:
      - ANVIL_IP_ADDR=0.0.0.0
    stdin_open: true
    tty: true
    networks:
      customnet:
        ipv4_address: 172.40.0.1

  foundry:
    image: ghcr.io/foundry-rs/foundry
    volumes:
      - ./simple-bank:/app/simple-bank          # 소스 ↔ 컨테이너 매핑
    working_dir: /app/simple-bank
    entrypoint: /bin/bash       # “bash 쉘”로 진입
    tty: true
    stdin_open: true
    environment:
      - ETH_RPC_URL=http://anvil:8545
    depends_on:
      - anvil
    networks:
      customnet:
        ipv4_address: 172.40.0.3

  frontend:
    image: node:22
    ports:
      - 10010:10010
    working_dir: /app/frontend
    volumes:
      - ./frontend:/app/frontend
    stdin_open: true
    tty: true
    networks:
      customnet:
        ipv4_address: 172.40.0.5

networks:
  customnet:
    ipam:
      config:
        - gateway: 172.40.1.1
          subnet: 172.40.0.0/16